application: 42btc-hackfisher
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(gif|png|jpg|css|js))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|css|js))

- url: /.*
  script: ticker.app
  
libraries:
- name: jinja2
  version: latest
  
inbound_services:
- channel_presence

